### ISSUE TITLE
Feedback on topic: Mentorship & contributors

### ISSUE THREAD

**Issue by arfon** [github/open-source-survey#10]
As described in the [`README`](https://github.com/github/the-open-source-survey#how-you-can-help), we'd love to hear from you about any existing survey instruments you know of that that explore the survey [topic areas](https://github.com/github/the-open-source-survey/blob/master/survey-topics.md) we're interested in.

Please use this issue to let us know about existing survey instruments and research on _Mentorship & contributors_:

> Software development is an unusual trade in that autodidacticism is common and people often learn from working with or observing others who are not geographically proximate and will likely never meet face to face. Nonetheless, previous research has demonstrated that 1:1 help and mentorship are critical to building skills, confidence, and professional networks. How do beginners seek and select mentorship within the open source community? What motivates some individuals to make casual (one-off) contributions to new projects rather than finding a mentor and diving deep into a project and a community? How do people willing to mentor make that known, and how do they select mentees?

**Comment by gousiosg** [comment]
We, @gousiosg, @margaretstorey and @sback, have done a survey (750 participants) of the work habbits and the challenges faced by OSS contributors using the pull request model. See our [paper](http://gousios.org/bibliography/GSB16.html) and our [repository](https://github.com/gousiosg/pullreqs-contributors) with all data (including the survey), tools and analysis results. Let me know if I can help with your survey.

**Comment by arfon** [comment]
> We, @gousiosg, @margaretstorey and @sback, have done a survey (750 participants) of the work habbits and the challenges faced by OSS contributors using the pull request model. See our paper and our repository with all data (including the survey), tools and analysis results. Let me know if I can help with your survey.

👍  many thanks @gousiosg  @margaretstorey and @sback. We'll definitely take a look.

**Comment by arfon** [comment]
Many thanks for the feedback here @gousiosg, @margaretstorey and @sback. We're going to be incorporating this and the feedback on [other feedback issues](https://github.com/github/open-source-survey/labels/help%20wanted) in the survey topics and instrument which we plan to share publicly soon.
