### ISSUE TITLE
Bad link in readme on this repo for @arfon's thesis (HTTP Status 404 - Not Found)

### ISSUE THREAD

**Issue by MrCull** [github/open-source-survey#103]
In the readme for this repo there is a link to @arfon's thesis: https://www.arfon.org/thesis
However this link is now dead (HTTP Status 404 - Not Found).
I've had a look on afron's website but cannot see this document under another link.

Could you advise @arfon if this link can be found elsewhere?
If not then possibly this link could be used instead(?): https://www.arfon.org/#-some-background

## Extra info
I found this using a new tool that I recently recreated that uses the GitHub API:
https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

This tool can be used to find bad links in repo's readme files.

See example url below that will re-check this repo:
http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fgithub%2fopen-source-survey

I'd love to hear some feedback on this tool, especially from someone at GitHub, so feel free to pass on any comments or suggestions etc...

**Comment by arfon** [comment]
Fixed in https://github.com/github/open-source-survey/commit/66ed52fe1462bab0e034d2c000366eb1c0df1f44. Thanks for the heads up @MrCull.
