### ISSUE TITLE
Feedback on topic: Demographics

### ISSUE THREAD

**Issue by arfon** [github/open-source-survey#14]
As described in the [`README`](https://github.com/github/the-open-source-survey#how-you-can-help), we'd love to hear from you about any existing survey instruments you know of that that explore the survey [topic areas](https://github.com/github/the-open-source-survey/blob/master/survey-topics.md) we're interested in.

Please use this issue to let us know about existing survey instruments and research on _Demographics_:

> How representative is open source of the software developer community? Of the world population? How do these characteristics correlate with experiences, motivations, and other aspects of participation in open source?

**Comment by igorsteinmacher** [comment]
Hi all,

hope these can help you:
https://docs.google.com/forms/d/1kJgf1l7qP6t6Xcynxo3dfe_SyFubHmKqGb7ZnsIxdTc --> Contributors (casual contributions)
https://docs.google.com/forms/d/1SCvF29LVuwE3fopLlA4BAeqUxJZOIqXt4jB4k_obQXM --> Contributors (casual contributions)
https://docs.google.com/forms/d/1hs49Tum6NS4d51RQpWxL2wc2nMQf3Hzcli4szwQIXvs --> Onboarding
http://igor.pro.br/limesurvey/index.php/survey/index/sid/89755/newtest/Y/lang/en --> Onboarding

**Comment by arfon** [comment]
😍 @igorsteinmacher, many thanks for these links!

**Comment by arfon** [comment]
Many thanks for the feedback here @igorsteinmacher. We're going to be incorporating this and the feedback on [other feedback issues](https://github.com/github/open-source-survey/labels/help%20wanted) in the survey topics and instrument which we plan to share publicly soon.
