### ISSUE TITLE
Replace references to "fall" with hemisphere-neutral terminology

### ISSUE THREAD

**Issue by frasertweedale** [github/open-source-survey#29]
*Fall* does not happen at the same time in the northern and southern hemispheres.

Besides, many English-speaking countries call that season "autumn".

Please do not ostracise non-American folk :)

**Comment by tagawa** [comment]
@frasertweedale Agree. This has been fixed and merged with this pull request: https://github.com/github/open-source-survey/pull/28

**Comment by frasertweedale** [comment]
Thanks, I didn't see #28.  But there are more references that were
missed:

- `open-source-survey/docs/_layouts/default.html:12` (this seems to be the source for http://opensourcesurvey.org/ front page)
- `open-source-survey/docs/_config.yml:18`

**Comment by mlinksva** [comment]
Thanks. If you notice any other unnecessarily geo/cultural/jurisdictionally-specific language, please continue to point out in new issues or pull requests.
