### ISSUE TITLE
Github robots giving false positives

### ISSUE THREAD

**Issue by hhsadiq** [github/open-source-survey#34]
I am an active github user working with two organisations. I push code almost on daily basis and participate in issues discussion for various libraries. Recently github robots blocked my profile from public when I reported an issue for EduSec repo. I reported this problem at support and profile was restored in less than half an hour. I was actively working from my office and this blockage caused panic for me. I think the NOT SO HARMLESS robots are programmed with weird too-strict rules. It would be great if you guys can revise the rules, to avoid false positives.

**Comment by bkeepers** [comment]
Hi @hhsadiq, please [contact GitHub support](https://github.com/contact) with any issues related to your account. This repository is for coordination on an industry-wide survey about open source software and the people that create it.

**Comment by hhsadiq** [comment]
Ah sorry for reporting this in wrong place. Your answer appreciated. Thanks
