### ISSUE TITLE
Expanding Demographics to Include Inclusion

### ISSUE THREAD

**Issue by anjuan** [github/open-source-survey#35]
The Demographics section of the survey seems to focus on diversity by asking about how representative the open source community is with regards to the developer community and the world population. However, what about expanding this to also discuss inclusion? 

I think that talking about how representation in open source correlates "with experiences, motivations, and other aspects of participation in open source" is hints at the topic of inclusion, but can this section also explicitly ask something like, "How inclusive is open source when it comes to contributions from underrepresented groups?" Or, maybe, "Why do certain demographic groups not contribute to open source software development?"

As it currently stands, the Demographics section is like a downtown restaurant asking, "Who are the people who come into our restaurant at lunch time?" That's an important question to answer, but I think a useful followup question would be, "Why are some people **not** coming into our restaurant at lunch time?" That's why I think this section should be expanded to explicitly inquire about inclusion.

**Comment by franniez** [comment]
Thanks for bringing this up, @anjuan; this is definitely in line with our goals and intentions, though I can see that it isn't necessarily clear from the topics document. We're getting at some of aspects of inclusion in the [community safety](https://github.com/github/open-source-survey/blob/master/survey-topics.md#community-safety) section, where we will be asking about experiences with harassment and abuse. However, there are experiences and dynamics that can discourage participation without rising to the level of explicit harassment, and we do plan to explore those as well.

**Comment by debbryant** [comment]
For post graduate research completed a few years back on Barriers to Participation in Communities which explored gender, language and other considerations, consider contacting Prof. Carlos Jenson at OSU.  The research may help inform your questions (or just be of general interest). 

Deb

**Comment by bkeepers** [comment]
The survey instrument was released today (#36), and includes [questions related to to inclusiveness](https://github.com/github/open-source-survey/blob/master/survey-instrument.md#harassment--inclusiveness-of-oss). Let us know if you have any questions or concerns.
