### ISSUE TITLE
I'd like to suggest a survey topic: financial support

### ISSUE THREAD

**Issue by BenJam** [github/open-source-survey#44]
I am interested in the proportion of projects that currently or have in the past received direct or indirect financial support for their work. I am also interested in whether this support was used to fund the time of contributors as opposed to incidental (hardware, travel, accommodation, food et al) costs. The current workplace topic:

>Much open source development is subsidized [sic] by companies, who either employ engineers to work on open source projects, or allow them to work on those projects when they also provide value to the firm. We’d like to explore how supported developers feel by their employers to contribute to open source

explores some aspects of this but I think a wider interpretation/appreciation would provide a more comprehensive overview of how under financed this community is and help some move the discussion regarding under-supported, 'core infrastructure' forward.

**Comment by bkeepers** [comment]
Hey @BenJam, thanks for the suggestion! The [survey instrument is already finalized](https://github.com/github/open-source-survey/blob/master/survey-instrument.md) for this year, but I think that will be a great topic to consider adding next year.

**Comment by MikeMcQuaid** [comment]
Closing as this is finalized for this year. Also, HI @BenJam!
