### ISSUE TITLE
Feedback on translations

### ISSUE THREAD

**Issue by bkeepers** [github/open-source-survey#47]
We are looking for feedback on [translations](https://github.com/github/open-source-survey/blob/master/translations/) of the [survey instrument](https://github.com/github/open-source-survey/blob/master/survey-instrument.md). If you are fluent in any of these languages, we would love help reviewing the translations.

- [x] [Chinese](https://github.com/github/open-source-survey/blob/master/translations/oss-survey-chinese.txt) (Traditional)
- [x] [Japanese](https://github.com/github/open-source-survey/blob/master/translations/oss-survey-japanese.txt)
- [x] [Russian](https://github.com/github/open-source-survey/blob/master/translations/oss-survey-russian.txt)
- [x] [Spanish](https://github.com/github/open-source-survey/blob/master/translations/oss-survey-spanish.txt)

If you review a translation and it looks good to you, could you comment with a 👍 here.

If you find any issues with a translation, could you open a pull request to suggest changes and find at least one other person that is fluent in that language to check it out?

*Update:* There's also a [glossary of terms](https://github.com/github/open-source-survey/blob/master/translations/glossary.md).

**Comment by bkeepers** [comment]
Heads up! The Spanish translation is already being revised by some folks at GitHub.

**Comment by ashchan** [comment]
The Chinese content is actually in Traditional Chinese. If you have a Simplified Chinese version I can help reviewing.

**Comment by PeterDaveHello** [comment]
I can take care of Traditional Chinese and maybe a draft of Simplified Chinese :smile:

**Comment by bkeepers** [comment]
> The Chinese content is actually in Traditional Chinese. If you have a Simplified Chinese version I can help reviewing.

Hey @ashchan, thanks for offering to help!

We can work on adding a Simplified Chinese translation next time we run the survey, but due to time constraints, we won't be able to do it this year. To clarify why we're doing Traditional Chinese and not Simplified Chinese: We chose these languages based on the most popular visitors to GitHub.com.

**Comment by bkeepers** [comment]
There's also a [glossary of terms](https://github.com/github/open-source-survey/blob/master/translations/glossary.md), which I've added to the original post.

**Comment by zafarella** [comment]
@bkeepers  some corrections to russian text #50

**Comment by annafil** [comment]
Some more corrections to the Russian text #55

**Comment by bkeepers** [comment]
Thanks to everyone for your help in fixing up the translations! It is greatly appreciated. There is still one more PR (https://github.com/github/open-source-survey/pull/56) being worked through, but I'm going to close this since we aren't actively seeking feedback on the other translations.
