### ISSUE TITLE
German Translation needed?

### ISSUE THREAD

**Issue by michaeldorner** [github/open-source-survey#57]
Do you need/wish a German translation?

**Comment by bkeepers** [comment]
Hey @michaeldorner, thanks for asking!

To quote from https://github.com/github/open-source-survey/issues/47#issuecomment-273580060

> We can work on adding a Simplified Chinese translation next time we run the survey, but due to time constraints, we won't be able to do it this year. To clarify why we're doing Traditional Chinese and not Simplified Chinese: We chose these languages based on the most popular visitors to GitHub.com.

Same applies to German. We'd love to have one next time we run the survey.
