### ISSUE TITLE
turning GitHub.com into a intelligent "all-ware" metaframework

### ISSUE THREAD

**Issue by tiagmoraismorgado** [github/open-source-survey#59]
Heyho everyone

Github is already, within itself, an awesome tool. Thanks to it I've been able of engaging within open source development, engaging with new people, eventually even finding work. Even though, I think it would be awesome to turn GitHub into an intelligent allware metaframework. what do I mean with this?

- that all GitHub code would be turned into a single framework, that could even be hosted online;
- this code would be able to embed and cross bind any language;
- high level actions would be turned into boxes, just like in scratch;
- you could connect these boxes to make new apps, and then just compiling them out;
- you could constantly add new functions in between;
- this could all be done using a graphic interface similar to what you find in quartz composer, vvvv, touch designer, or the unreal engine blueprint
- you could turn new user modules into new commands, and making apps out of apps
- you could group actions by classes. and make mutant programs, by recombining all the called objects using objects from the same classes

**Comment by oldmud0** [comment]
GitHub is intended to be a collaboration service for source code that already exists. I don't think creating a framework of this immensity is in their roadmap, but you could perhaps look to another to see what people think of your ideas.

**Comment by bkeepers** [comment]
Thanks for the suggestion @tiagmoraismorgado, but it is beyond this scope of this repository, which is for a survey on open source.
