### ISSUE TITLE
first option in question 31 in the Open-Source-Survey blanks out all other options

### ISSUE THREAD

**Issue by janjaapdriessen** [github/open-source-survey#62]
It looks like the first option in question 31 of the Open-Source-Survey has the "none-of-the-above" behavior. I don't know whether that's the intended implementation? If this is a bug in setting up the survey, you might be losing data. Same could be the case for question 32.

**Comment by franniez** [comment]
@janjaapdriessen Thanks very much for letting us know about this- that was indeed an error and it should be fixed now. We'll flag responses collected prior to the fix as incomplete when we do the public data release.
