### ISSUE TITLE
Suggest clarification around "first access to a computer with internet"

### ISSUE THREAD

**Issue by kornysietsma** [github/open-source-survey#66]
I suspect the questions about "when did you first have access to a computer connected to the internet" is a bit misleading when it comes to older developers like myself, who had access to computers before there _was_ a public access internet to connect to.

Maybe this should be "first have access to a computer connected to the internet or other public networks such as BBSs"?  Unless the intent is genuinely about use of the internet - in which case you still might need clarification that this is the case.

**Comment by franniez** [comment]
This particular question is intended to be about the internet specifically, and we’re limiting edits (except things like typos) as much as possible while we’re in the middle of data collection. But, this is a good point and in the future we should ask more and better questions about access to and use of computers pre-internet, particularly to engage with other people.  On the list for next year’s survey  😄

**Comment by MikeMcQuaid** [comment]
Great idea 👍. Closing this out just for this year's survey.
