### ISSUE TITLE
Q 30: Observations of events in the context of an open source project

### ISSUE THREAD

**Issue by m-kuhn** [github/open-source-survey#74]
This is a rally nice survey, I'm glad to have participated.

There is one question however, that made me a bit concerned, in particular Question 30. "Have you ever observed any of the following in the context of an open source project?".
The conclusions one can draw from this questions are obvious. At the same time I am convinced that in *any* project in *any* context, where humans are involved, one would answer every question with *yes* after having spent enough time within this setting.

I think these questions should allow answers on a scale between "never" and "very often" to allow estimating the importance of such events. Any conclusion drawn from the current answers (yes/no) will be completely meaningless.

**Comment by garrettw** [comment]
I disagree. I answered "no" to two of the options, so I would think they can get an idea of the prevalence of each one by how high the "yes" percentages are.

**Comment by bkeepers** [comment]
@m-kuhn Thanks, that's great feedback. We'll be running the survey every year, so when we look at the results, we'll keep this in mind and consider adjusting it next year.
