### ISSUE TITLE
Please identify yourself on the survey

### ISSUE THREAD

**Issue by LemmingAvalanche** [github/open-source-survey#75]
The survey just says “we”.  It doesn’t say that it is GitHub that is behind it.
Granted that the survey is accessed from GitHub, but I don’t think it would hurt
to be more clear about it.  First of all, I thought that there might be some
third party that had permission to request stuff from GitHub users.  Secondly,
one might open pages like the survey in a new tab and only get back to the page
later, at which point you might have closed the tab from which you accessed the
survey, and forgot the exact context in which you ended up clicking on the
survey.

**Comment by bkeepers** [comment]
Hey @LemmingAvalanche, this is great feedback. We tried really hard to make this a survey for the _community_ and not for GitHub, but you're right that we should at least name that GitHub is leading it.

**Comment by MikeMcQuaid** [comment]
As the survey has now started passing on this for now, thanks.
