### ISSUE TITLE
"Real" name? 

### ISSUE THREAD

**Issue by azurelunatic** [github/open-source-survey#76]
The language in the survey instrument puts "real name" and "pseudonym" in contrast with each other. 

What is the "real name" that you're talking about? Is it one's legal name (or a derivative, such as someone named Alice who goes by Allie), is it one's professional name (the name one's co-workers and boss calls one, and the name on your resume), or is it the name that one feels is most legitimately and deeply theirs (such as the name that their partner or closest friends call them)? 

For many people, these are the same thing. 

For those people where these are not the same, what are you interested in hearing about?

**Comment by franniez** [comment]
@azurelunatic Of the typology above, professional name is the closest to what we are interested in.
