### ISSUE TITLE
Q40 makes no distinction between copyleft and non-copyleft licenses

### ISSUE THREAD

**Issue by bjmc** [github/open-source-survey#77]
Right now, Q40 reads

> Which is closest to your employer’s policy on incorporating open source dependencies into your codebase?

Many employers (and their legal departments) are very skittish about incorporating dependencies on GPL-licensed (and [copyleft](https://en.wikipedia.org/wiki/Copyleft) generally) code, but accepting or even encouraging of using MIT- or BSD-licensed (non-copyleft) dependencies.

As it stands, Q40 is difficult to answer accurately because it makes no distinction between these two different categories of licensing.

**Comment by bkeepers** [comment]
Hey @bjmc, thanks for the suggestion. We intentionally wanted to stay away from topics related to specific licenses, but your feedback makes me wonder if we should could clarify this question to include something about legal review. We'll take it into consideration next year!

**Comment by MikeMcQuaid** [comment]
As the survey has now started passing on this for now, thanks.
