### ISSUE TITLE
Looking for off-site communities

### ISSUE THREAD

**Issue by franniez** [github/open-source-survey#83]
We're looking for more off-site open source communities to participate in the [off-site sample](https://github.com/github/open-source-survey/blob/master/sampling.md#sampling-off-github)! If you are part of a community that works primarily somewhere other than GitHub (e.g. hosted elsewhere, or via mailing list, etc.), please [fill out this form](https://docs.google.com/forms/d/e/1FAIpQLSfiZZr-WLls6b8BCZdtyi__wrFzqtplP-YmGw25CAx3rLvlXw/viewform?c=0&w=1) and we'll send you a community-specific link and email template to share.

**Comment by emaste** [comment]
Are you looking for survey responses specifically from developers of non-GitHub-hosted projects, or from any member of the broader community associated with a project?

**Comment by franniez** [comment]
Any member! We're interested in hearing from anyone engaged with an open source project, definitely not just developers.

From our [design principles](https://github.com/github/open-source-survey/blob/master/design-principles.md#open-source-community): 

> The universe of this study is anyone who uses or otherwise engages with open source technology and development, whether passively or actively through contributions. This is a broader definition of this community than commonly employed, and we believe one of the major contributions of this study will be a dataset that allows for exploration of open source consumers alongside contributors.

**Comment by MikeMcQuaid** [comment]
The survey 🚢d! 🎉
