### ISSUE TITLE
BibTex entry for easier citation

### ISSUE THREAD

**Issue by chrisma** [github/open-source-survey#86]
The `README.md` in the "License" section states
> If you use this dataset in a publication, a link to or citation of this repository would be appreciated.

Who should be attributed as the author(s), `GitHub, Inc.`?
Would it be possible to provide a [BibTex](http://www.bibtex.org/Format/) entry or even a [DOI number for the repository](https://guides.github.com/activities/citable-code/) to allow easier citations?

E.g.
```
@misc{OpenSourceSurvey17,
  author = {GitHub, Inc.},
  title = {Open Source Survey},
  year = {2017},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/github/open-source-survey}}
}
```

**Comment by arfon** [comment]
I would recommend publishing the data with Zenodo.org (https://zenodo.org) which will give you both a DataCite DOI but also an easy way for folks to generate BibTex entries as there's a link at the bottom-right of every Zenodo archive page e.g. https://zenodo.org/record/801828#.WTGQS8aZM3E

**Comment by chrisma** [comment]
Yup, Zenodo is also the service that GitHub itself recommends for assigning DOIs to repositories in their guide ([https://guides.github.com/activities/citable-code/](https://guides.github.com/activities/citable-code/)).

The service also offers a "badge", that can be included in the `README.md` 

![image](https://cloud.githubusercontent.com/assets/1652117/26735774/9f566524-47c3-11e7-85c5-80c378caf4b9.png)

**Comment by arfon** [comment]
> I would recommend publishing the data with Zenodo.org (https://zenodo.org) which will give you both a DataCite DOI but also an easy way for folks to generate BibTex entries as there's a link at the bottom-right of every Zenodo archive page e.g. https://zenodo.org/record/801828#.WTGQS8aZM3E

👋 @franniez - would it be helpful for me to do this? If so, who should I list as authors?

**Comment by franniez** [comment]
Apologies for the delay and thanks for the reminder ping, @arfon! Added some citation info, including a DOI, in https://github.com/github/open-source-survey/pull/90.
