### ISSUE TITLE
HTTPS missing from URL

### ISSUE THREAD

**Issue by nayafia** [github/open-source-survey#96]
Hi! I was linking to http://opensourcesurvey.org/ today and realized it's not HTTPS. Not sure if it simply expired, or whether it wasn't ever added, but it'd be great to have a secure URL to link to.

Thanks!

**Comment by mlinksva** [comment]
It wasn't ever added. 😊 Pages now supports directly, but it seems I'm not an admin for this repo to turn on...working on it. Thanks!

**Comment by shankaryoga21** [comment]
# @

**Comment by mlinksva** [comment]
Apologies for delay: https://opensourcesurvey.org/2017/

**Comment by nayafia** [comment]
Yay! Thanks for doing this!
