### ISSUE TITLE
HSTS for opensourcesurvey.org

### ISSUE THREAD

**Issue by lgarron** [github/open-source-survey#97]
opensourcesurvey.org supports HTTPS as of #96. It would be great to go all the way with preloaded HSTS: https://hstspreload.org/?domain=opensourcesurvey.org

GH Pages supports HSTS headers, but it's not available externally yet so a Hubber like me needs to set it manually. Would it be alright for me to set the header to `Strict-Transport-Security: max-age=63072000; includeSubDomains; preload`?

**Comment by mlinksva** [comment]
Please do!

**Comment by lgarron** [comment]
*woo!*

<img width="905" alt="screen shot 2018-12-07 at 14 48 39" src="https://user-images.githubusercontent.com/248078/49676614-3be3ec80-fa2f-11e8-8ef5-e21fdf178277.png">
